[theme]
name = sphinx_icore_open
inherit = alabaster
stylesheet = css/theme.css
javascript = js/theme.js

[theme.pygments_style]
default = default

[options]
show_relbar_bottom = true
show_related = false
logo = _static/img/logo.svg
logo_text = iCore Open Sphinx Theme
slogan = iCore Open Sphinx Theme
meta_footer = A theme for Sphinx documentation
show_copyright_privacy_block_footer = false
copyright_url =
privacy_url =
home_url = /
