name: Publish

permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-24.04
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Build static files
        shell: sh
        run: npm run build

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Python 3.13
        run: uv python install 3.13

      - name: Build python package
        run: uv publish
